### ISSUE TITLE
Add PAS functions similar to PVS

### ISSUE THREAD

**Issue by JarosLucky** [RaphaelIT7/gmod-holylib#1]
Perhaps a description is not required? We have very few opportunities to obtain PAS, which may be useful in some cases

**Comment by RaphaelIT7** [comment]
I think I saw an issue somewhere about this in Gmod and I wanted to add some functions, but I didn't look into the PAS yet, so I don't know what's possible and how it works

**Comment by RaphaelIT7** [comment]
So I looked into it a bit and I don't think the engine has many PAS functions, so I would need to make my own.
What functions would be useful for PAS?

**Comment by WinterPhoenix** [comment]
ents.FindInPAS and ENTITY.TestPAS would be fantastic.

Without TestPAS for example, one has to CRecipientFilter:AddPAS, then CRecipientFilter:GetPlayers, then check if the player is in the list, if you want to determine if a specific player can hear a position

**Comment by RaphaelIT7** [comment]
So currently I got `pas.TestPAS` working which should allow you to already most things.   
`pas.FindInPAS` will be added a bit later.  
( I should find better names for thoes :| )

**Comment by RaphaelIT7** [comment]
I don't think I can get 64x running with it so it'll be 32x only in the next release

**Comment by RaphaelIT7** [comment]
Finally..........
64x is there.......
(I didn't 100% test it but it seems to mostly work)
