### ISSUE TITLE
SubMaterial

### ISSUE THREAD

**Issue by DatGuy64** [RaphaelIT7/gmod-holylib#18]
Hi, currently in gmod you can't use SetSubMaterial on index superior to 31. is this something you can achieve ?

![image](https://github.com/user-attachments/assets/03d3a3bc-f346-4896-9a1c-b6404e076c59)

**Comment by RaphaelIT7** [comment]
If I remember correctly, submaterials internally used an array internally to set & network it.
Funnily enough, it uses the networkstrings like many other functions which means it's also limited to 4096 which is shared with stuff like util.AddNetworkString, NW and so on.

So I don't think I can do anything about that.
