### ISSUE TITLE
Death hook clientside

### ISSUE THREAD

**Issue by DatGuy64** [RaphaelIT7/gmod-holylib#19]
Add a hook that trigger when a player or when the localplayer die (could be useful)

**Comment by RaphaelIT7** [comment]
I don't think I can just add a clientside hook for that.
What I could do is add a gameevent, but then I think using the entity_killed or player_hurt gameevent would already work.

**Comment by DatGuy64** [comment]
i've tried to use "entity_killed" and "player_hurt" but it does nothing or maybe i can only use it on a dedicated server ?

**Comment by RaphaelIT7** [comment]
they do nothing?
like they aren't called in any way?

**Comment by DatGuy64** [comment]
``` lua gameevent.Listen( "entity_killed" )
hook.Add( "entity_killed", "test", function( data ) 
	local inflictor_index = data.entindex_inflictor
	local attacker_index = data.entindex_attacker
	local damagebits = data.damagebits
	local victim_index = data.entindex_killed
	
	print(victim_index)
	print("killed")
	PrintTable(data)
	print("killed")
end )
```
no print at all (same for player_hurt)

**Comment by RaphaelIT7** [comment]
did you call gameevent.Listen? xd

**Comment by DatGuy64** [comment]
yes i've edited the comment

**Comment by DatGuy64** [comment]
i remember trying to use theses gameevent a long time ago for my gamemode (do thing when you deal damage to a player) since it didn't work i was forced to use net message 

btw i use player_connect event and this one work fine so.. i don't know :/

**Comment by RaphaelIT7** [comment]
when I'm home I'll look into it, but I remember those gameevents working

**Comment by DatGuy64** [comment]
thanks (maybe it only work on dedicated server) ¯\\_(ツ)_/¯

**Comment by RaphaelIT7** [comment]
![image](https://github.com/user-attachments/assets/f113ae26-ec92-44a0-b2d8-543dd2ca2f1a)
Works for me ._.

**Comment by DatGuy64** [comment]
Wtf is there a way for an addon to disable mine ?

**Comment by RaphaelIT7** [comment]
As far as I know only by detouring gameevent.Listen or the hook library to specificly exclude that gameevent.

**Comment by DatGuy64** [comment]
Ok i've disabled all my workshop and it caused by that now it work (my bad) i don't know why someone would prevent them from be used. now i just need to find what addon is doing it

**Comment by DatGuy64** [comment]
i can't find why theses 2 gameevent are not getting called :/

i saw that https://wiki.facepunch.com/gmod/GM:ScalePlayerDamage is called clientside when you deal damage to a player (but not when you receive damage) maybe you can find a way to add a clientside hook based on this one ?

if not you can just close this issues and thanks for your help 👍

**Comment by RaphaelIT7** [comment]
I'll later add a documentation on how to make custom gameevents and how to network them properly after I finished the new wiki, but other than that I can't really do much, especially clientside. At best, I could network a lua_run every time, but that also would be quite a workaround.
So using net messages, user messages or gameevents should be the only way to go.
