### ISSUE TITLE
Add function for querying Steam connection status

### ISSUE THREAD

**Issue by WinterPhoenix** [RaphaelIT7/gmod-holylib#3]
Sometimes the server will lose connection to Steam, most likely because of maintenance. During this time, players can’t authenticate, which prevents connecting to the server unless it’s in LAN mode.

Occasionally, you’ll also get an assertion failure like this:
```
Connection to Steam servers lost. (No internet connection)
src/clientdll/cminterface.cpp (3568) : m_VecNetAdrNetFilterCMs.Count()
src/clientdll/cminterface.cpp (3568) : m_VecNetAdrNetFilterCMs.Count()
```

Which breaks whatever Steam auto-reconnection logic SRCDS has, and it won’t reconnect until the server is manually restarted.

What I propose is a function to query Steam connection status, so that if this happens and the Steam connection is down too long, we’ll be able to do something about it, like restart the server automatically.

An even better alternative would be the ability to force the server to attempt to reconnect, and even better than that would be some patch that prevents auto-reconnection breaking in the first place, but I know that’s a big ask.

**Comment by RaphaelIT7** [comment]
I added 3 new functions `steamworks.Shutdown()`, `steamworks.Activate()` and `steamworks.IsConnected()`.
I also added two new hooks. `HolyLib::OnSteamDisconnect(number result)`, `HolyLib::OnSteamConnect()`

**Comment by WinterPhoenix** [comment]
very cool! thanks for the WICKED fast implementation
