### ISSUE TITLE
TableToJSON that actually respects things like integers.

### ISSUE THREAD

**Issue by NathanX-S** [RaphaelIT7/gmod-holylib#6]

**Comment by RaphaelIT7** [comment]
I'll look into it tomorrow :D

**Comment by RaphaelIT7** [comment]
So just for tomorrow, you mean with respects integers that it stops to convert it to a decimal?

**Comment by NathanX-S** [comment]
Yup! More accurate/friendly conversions, especially for things like APIs.

**Comment by RaphaelIT7** [comment]
Does it only happen with integers or are there also other cases?
(Could imagine that since LUA->GetNumber returns a double that they just make it a decimal without checking if it is an Integer / has any decimals)

**Comment by RaphaelIT7** [comment]
I now check if the number has no decimals and also check if it's in the integer range/limits.
If it is, it will be made into one. I also noticed, it seems like my TableToJSON function is faster than gmods xd

Anyways, I'll test it a bit more and document it if I haven't yet.

**Comment by RaphaelIT7** [comment]
Should be done now. It should now also behave the same as Gmod's version (And it's still faster :D)
